### ISSUE TITLE
NFC tag behavior in comparison to a RFID tag (MIFARE 1K)  

### ISSUE THREAD

**Issue by noisesfromspace** [MohammadAG/NFCLockscreenoffEnabler#14]
Hello,

I have two wristbands, a MIFARE 1K wristband and a NTAG203 wristband. When using the MIFARE wristband it will unlock my phone and return to the current open application. When using my NTAG203 the device will unlock but will return to my launcher regardless of the open application. Is there any way to bypass this, or change this in the software. Sorry if this totally out of place.

**Comment by MohammadAG** [comment]
This module simply unlocks the device, so the currently open application should show up after that.
If it goes to the home screen with one tag, it's safe to say that it's because of what's on the tag itself, rather than the module.

**Comment by noisesfromspace** [comment]
Yes that could be so! Thanks and sorry for thrashing your repository!
